// Generated by FlutterFire CLI. Run: dart pub global activate flutterfire_cli && flutterfire configure
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO: Replace these with your real Firebase project config from https://console.firebase.google.com

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'SECRETTTTT',
    appId: '1:599668381855:web:ad8f9d6a413c86fa276aaa',
    messagingSenderId: '599668381855',
    projectId: 'projet-ds-ang',
    authDomain: 'projet-ds-ang.firebaseapp.com',
    storageBucket: 'projet-ds-ang.firebasestorage.app',
  );

  // Run: dart pub global activate flutterfire_cli && flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'SECREEEEET_-A',
    appId: '1:599668381855:android:6199e0ebdb50a613276aaa',
    messagingSenderId: '599668381855',
    projectId: 'projet-ds-ang',
    storageBucket: 'projet-ds-ang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'SECREEET',
    appId: '1:599668381855:ios:b935c3049ce82cfc276aaa',
    messagingSenderId: '599668381855',
    projectId: 'projet-ds-ang',
    storageBucket: 'projet-ds-ang.firebasestorage.app',
    iosBundleId: 'com.biolab.protein3dViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'SECRETTTTT',
    appId: '1:599668381855:web:12ed8c7253413c74276aaa',
    messagingSenderId: '599668381855',
    projectId: 'projet-ds-ang',
    authDomain: 'projet-ds-ang.firebaseapp.com',
    storageBucket: 'projet-ds-ang.firebasestorage.app',
  );

}